---
title: "ASSIGNMENT 10"
author: "Alexis Kwan"
subtitle: PA 434
output:
  pdf_document: default
  html_notebook: default
---

```{r, include=FALSE}
# devtools::install_github("thebioengineer/tidytuesdayR")
# install.packages("rcartocolor")
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(dpi=300,fig.width=7)
```

```{r, include=FALSE}
tuesdata <- tidytuesdayR::tt_load("2020-03-10")
tuition_cost <- tuesdata$tuition_cost
diversity_school <- tuesdata$diversity_school
library(tidyverse)
library(rcartocolor)
```

```{r}
th <- theme_minimal() + theme(
  plot.title = element_text(size = 20, face = "bold", hjust = 0.5),
  plot.subtitle = element_text(size = 16, face = "italic", hjust = 0.5),
  axis.title = element_text(size = 14),
  axis.text = element_text(size = 14),
  legend.title = element_text(size = 14),
  legend.text = element_text(size = 12)
)
```

# 1. Heatmap

```{r, fig.width=14, fig.height=12, message=FALSE}
tuition_cost %>%
  filter(!is.na(state)) %>%
  group_by(state, type) %>%
  mutate(avg_in_state_tuition = mean(in_state_tuition)) %>%
  ggplot(aes(x = type, y = state, fill = avg_in_state_tuition)) + 
  geom_tile() +
  labs(title = "Average College Tuition by State",
       x = "Type of College",
       y = "State",
       fill = "Average In-state Tuition") +
  scale_fill_carto_c(palette = "Emrld", direction = 1) +
  th
```

# 2. Lollipop Chart

```{r, fig.width=14, fig.height=12}
lollipop <-
  tuition_cost %>%
  left_join(diversity_school, by = c("name", "state")) %>%
  filter(state == "Illinois" &
           degree_length == "4 Year" &
           category == "Black") %>%
  filter(total_enrollment > median(total_enrollment, na.rm = TRUE)) %>%
  mutate(
    prop_enrollment = enrollment / total_enrollment,
    name = fct_reorder(as.factor(name), prop_enrollment)
  ) %>%
  ggplot() +
  geom_point(aes(x = prop_enrollment, y = name),
             size = 5,
             color = "#0072B2") +
  geom_segment(aes(
    x = 0,
    xend = prop_enrollment,
    y = name,
    yend = name
  ),
  color = "#0072B2") +
  geom_text(aes(
    x = prop_enrollment + 0.05,
    y = name,
    label = scales::percent(prop_enrollment, accuracy = 0.01)
  ),
  size = 6) +
  labs(title = "What proportion of university students are black?",
       x = "Proportion of Total Enrollment",
       y = "University") +
  scale_x_continuous(labels = scales::percent) +
  scale_color_brewer(palette = "Paired") +
  th
lollipop
```

# 3. Cleveland Chart

```{r, fig.width=14, fig.height=12}
cleveland <-
  tuition_cost %>%
  left_join(diversity_school, by = c("name", "state")) %>%
  filter(state == "Illinois" &
           degree_length == "4 Year" & 
           category == "Black") %>%
  filter(total_enrollment > median(total_enrollment, na.rm = TRUE)) %>%
  mutate(
    black = enrollment / total_enrollment,
    nonblack = 1 - black,
    name = fct_reorder(as.factor(name), black - nonblack)
  ) %>%
  pivot_longer(c("black", "nonblack"),
               names_to = "race",
               values_to = "prop_enrollment") %>%
  mutate(race = fct_recode(race,
                           "Black" = "black",
                           "Non-Black" = "nonblack")) %>%
  # select(name, category, prop_enrollment) %>%
  ggplot(aes(x = prop_enrollment, y = name)) +
  geom_line(aes(group = name), size = 1) +
  geom_point(aes(color = race), size = 5) +
  labs(title = "Proportion of College Students",
       subtitle = "Black versus Non-Black",
       x = "Proportion of Total Enrollment",
       y = "University",
       color = "Race") +
  scale_x_continuous(labels = scales::percent) + 
  scale_color_brewer(palette = "Paired", direction = -1) +
  th
cleveland
```
